### PR TITLE
Fix error when 'default' is disabled

### LINKED ISSUE #27: Mod claim to have an optional dependency on `default` but causes errors if it isn't enabled
The mod doesn't check if `default` is enabled when registering water nodes as lightable:

https://github.com/minetest-mods/wielded_light/blob/1487fb246eee98e426d98a0dc0bdf0940d2f40d0/init.lua#L634-L637

https://github.com/minetest-mods/wielded_light/blob/1487fb246eee98e426d98a0dc0bdf0940d2f40d0/init.lua#L640-L641

The mod should either hard depend on `default` or check if `default` is enabled.

### PR DESCRIPTION
**Pull request by Niklp09**
- Fix https://github.com/minetest-mods/wielded_light/issues/27
- Remove depends.txt (deps are present in mod.conf)

### CODE REVIEW

File: init.lua [hunk 1]
```diff
@@ -631,14 +631,16 @@ wielded_light.register_player_lightstep(function (player)
...
-wielded_light.register_lightable_node(water_name, nil, "water_")
-wielded_light.register_lightable_node("default:river_water_source", nil, "river_water_")
+
+if minetest.get_modpath("default") then
+	wielded_light.register_lightable_node("default:water_source", nil, "water_")
+	wielded_light.register_lightable_node("default:river_water_source", nil, "river_water_")
+elseif minetest.get_modpath("hades_core") then
+	wielded_light.register_lightable_node("hades_core:water_source", nil, "water_")
+else
+	error_log("Not running in a supported game, lightable water disabled")
```
Comment (AFCMS) [inline init.lua:642]: Could just not show any error here so all games will work if they don't have water.

Comment (Niklp09) [reply init.lua:642]: error_log will simply add a warning to the log, I thought it's maybe helpful for people who check the logs
